name: Release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Version
      id: version
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1

    - name: Cache Go
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: go mod download

    - name: Build Linux AMD64
      run: GOOS=linux GOARCH=amd64 go build -o kubectl-curl_${{ steps.version.outputs.tag }}_linux_amd64

    #- name: Build Linux ARM64
    #  run: GOOS=linux GOARCH=arm64 go build -o kubectl-curl_${{ steps.version.outputs.tag }}_linux_arm64

    #- name: Build Darwin AMD64
    #  run: GOOS=darwin GOARCH=amd64 go build -o kubectl-curl_${{ steps.version.outputs.tag }}_darwin_amd64

    #- name: Build Darwin ARM64
    #  run: GOOS=darwin GOARCH=arm64 go build -o kubectl-curl_${{ steps.version.outputs.tag }}_darwin_arm64

    #- name: Build Windows AMD64
    #  run: GOOS=windows GOARCH=amd64 go build -o kubectl-curl_${{ steps.version.outputs.tag }}_windows_amd64.exe

    #- name: Build Windows ARM64
    #  run: GOOS=windows GOARCH=arm64 go build -o kubectl-curl_${{ steps.version.outputs.tag }}_windows_arm64.exe

    - name: Generate Artifacts
      run: for bin in kubectl-curl_*; do tar czf $bin.tar.gz $bin LICENSE; done

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          LICENSE
          kubectl-curl_${{ steps.version.outputs.tag }}_linux_amd64.tar.gz
          kubectl-curl_${{ steps.version.outputs.tag }}_linux_arm64.tar.gz
          kubectl-curl_${{ steps.version.outputs.tag }}_darwin_amd64.tar.gz
          kubectl-curl_${{ steps.version.outputs.tag }}_darwin_arm64.tar.gz
          kubectl-curl_${{ steps.version.outputs.tag }}_windows_amd64.exe.tar.gz
          kubectl-curl_${{ steps.version.outputs.tag }}_windows_arm64.exe.tar.gz
