name: Release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: deps

    - name: Vendor
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod vendor

    - name: Build
      run: |
        go mod vendor
        GOOS=linux   GOARCH=amd64 go build -o kubectl-curl_linux_amd64
        #GOOS=linux   GOARCH=arm64 go build -o kubectl-curl_linux_arm64
        #GOOS=darwin  GOARCH=amd64 go build -o kubectl-curl_darwin_amd64
        #GOOS=darwin  GOARCH=arm64 go build -o kubectl-curl_darwin_arm64
        #GOOS=windows GOARCH=amd64 go build -o kubectl-curl_windows_amd64.exe
        #GOOS=windows GOARCH=arm64 go build -o kubectl-curl_windows_arm64.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          LICENSE
          kubectl-curl_linux_amd64
          kubectl-curl_linux_arm64
          kubectl-curl_darwin_amd64
          kubectl-curl_darwin_arm64
          kubectl-curl_windows_amd64.exe
          kubectl-curl_windows_arm64.exe
